import React from "react";
import PropTypes from "prop-types";

// core components
import Header from "../../components/header/header.jsx";
import HeaderBanner from "../../components/banner/banner.jsx";
import Footer from "../../components/footer/footer.jsx";
import ScrollToTopOnMount from '../../components/Scroll/scrollToTop';

// sections for this page
import TabelaDePreco from "./Sections/tabelaDePreco";

const CandidatosInscritos = () => {
    return (
        <div id="main-wrapper">
            <ScrollToTopOnMount />
            <Header />
            <div className="page-wrapper">
                <div className="container-fluid">
                    <HeaderBanner />
                    <h2 style={{ textAlign: 'center', paddingTop: '20px', color: '#ff0000', fontFamily: 'Batang' }} >
                        CANDIDATOS DA DEMOCRACIA DO POVO
                    </h2>
                    <div style={{ display: 'flex', justifyContent: 'center', padding: '25px' }}>
                        <div style={{ border: '2px solid green' }}>
                            <p style={{ textAlign: 'justify', color: '#000', padding: '20px', fontSize: '20px', display: 'flex', flexWrap: 'unset', fontFamily: 'Garamond' }}>
                                Os candidatos aos cargos políticos aqui inscritos se comprometem a trabalhar pela implantação da Democracia do Povo, por entenderem que somente se o eleitor puder votar em projetos, o trabalho e a renda poderão ser valorizados, com o aumento do salário mínimo para R$4.673,06 (DIEESE – abril/2020) e com a geração de 15 milhões de empregos diretos.
                                Se depender do Congresso Nacional e do governo executivo, essa possibilidade é nula, pois as leis trabalhistas, com o subterfúgio da proteção ao trabalhador, o escraviza, com baixa remuneração em troca de supostos benefícios, que o deixa sem forças para lutar pela sua liberdade e independência. Essa situação imita o patrão mal-intencionado (Sr. Vicci Ozo), que para manter o empregado em suas mãos, se dispõe a ser o fiador da locação de sua moradia, a financiar a compra de seu carro, descontando, de seu salário, o valor das parcelas, a fazer doações e presentear a sua família, a convidá-lo às festas e passeios e tantos outros “benefícios”, como até o de ser o seu padrinho de casamento ou de seu filho, mas lhe pagando salário de fome.
                                Alterando a Lei do Simples Nacional, a pequena empresa terá condições de arcar com esses compromissos, que a favorecerá com o aumento do consumo e com o aquecimento da economia.
                                Alguns economistas, de cara, dizem que o aumento do salário mínimo para aquele valor, causaria uma enorme inflação, mas a Democracia do Povo prova matematicamente, em sua revista de 44 páginas, inserida neste site, que os preços não aumentam proporcionalmente ao aumento do salário e, ao contrário, o consumo aumentaria 87% em relação ao atual poder de compra.
                                Aumentando o consumo, a produção terá de ser maior, e sendo, o mercado absorverá 15 milhões de trabalhadores. Esse número não foi, no projeto, jogado aleatoriamente e está também descrito na citada revista, com várias simulações da nova tributação para a pequena empresa — o Novo Simples da Democracia do Povo.
                                O atual Simples é simplesmente criminoso, ao empreendedor, à geração de empregos e até ao próprio Estado. As tabelas de alíquotas crescentes vão na contra mão do conceito de economia de escala. Mais dia, menos dia, muitas empresas abrem o bico, morrem, desempregam e deixam de crescer e de contribuir com o aumento da arrecadação de impostos. E se não crescem viram empresas medíocres, centenas de milhares de empresas “fundo de quintal”, sonegando e empregando informais com subsalários.
                                Uma empresa em crescimento cria poder de compra e consequentemente ganha descontos expressivos de seus fornecedores e com isso o empresário repassa parte do desconto ao seu cliente. Isso é economia de escala, mas com o Simples é diferente: quanto mais a empresa faturar, maior será a alíquota do Simples. Pode parecer um detalhe insignificante, mas o projeto do Novo Simples da Democracia do Povo, com as alíquotas decrescentes e mais uma opção de tributação proporciona a geração de 15 milhões de empregos e havendo menor procura por vagas de empregos, automaticamente, o empregador oferece maior valor de salário e a arrecadação de impostos aumenta consideravelmente. E a pequena empresa empregando mais de 30 milhões de pessoas independentes das “esmolas” (benefícios sociais) os encargos trabalhistas, segundo projeto do Novo Simples, serão reduzidos em 5% ao mês e repassados aos pisos salariais. Na segunda fase de aumento do salário mínimo para R$4.673,06, durante um período de 24 meses, a pequena empresa se fortalecerá com o consumo aumentando extraordinariamente, porém permanecendo o mesmo índice atual da folha de pagamento de salários, em relação ao faturamento. Esse e demais cálculos constam no projeto do Novo Simples descrito na citada revista.
                                Seguem dois exemplos de economia de escala: 1º - Um produto made in china é vendido por 5 reais e um produto nacional, por 15 reais. O lucro da empresa chinesa é de 1% e o lucro da empresa brasileira é de 10%. A empresa chinesa produz 1 milhão de peças ao mês. A empresa brasileira produz 10 mil peças. Quem ganhou mais dinheiro?  Gerou mais empregos? Contribuiu com maior arrecadação de impostos ao seu país?
                                2º - O lanche Big Mac nos EUA é 56% mais caro do que no Brasil. Nos EUA, o americano que ganha um salário mínimo consegue comprar cerca de 7 lanches por dia. No Brasil, o brasileiro que ganha um salário mínimo consegue comprar menos de 2 lanches por dia. Em qual dos dois países o índice de obesos é maior?
                    </p>
                            <p style={{ textAlign: 'justify', color: '#000', padding: '20px', fontSize: '20px', display: 'flex', flexWrap: 'unset', fontFamily: 'Garamond' }}>
                                No entendimento da Democracia do Povo, os candidatos aos cargos políticos têm somente duas posições a se colocarem: imitando o patrão Sr. Vito Ozo ou o patrão Sr. Vicci Ozo. E o eleitor, que é o trabalhador e o consumidor, também, têm duas opções: a de trabalhar na empresa do Vito ou do Vicci. Se pretender trabalhar na do Vito, terá de votar nos candidatos aqui inscritos e se votar em alguns dos que não estão inscritos continuará a receber as costumeiras benesses (vales, bolsas, cotas, FGTS, previdência, 13º, “direitos adquiridos”, SUS, educação pública de “graça”, segurança insegura pública, Transporte: um direito do cidadão; um dever do Estado), em troca de seu voto, de quatro em quatro anos.
                                O transporte público sob o esquema traiçoeiro que bolaram para extorquir dinheiro público é publico somente neste aspecto. Na realidade dos fatos e da lei, o transporte público não é um dever do Estado e um direito do cidadão e sim, um direito do Estado em gastar dinheiro dos impostos pagos por toda a população para sustentar o sistema de transporte público e um dever do cidadão em pagar a passagem do ônibus e os impostos que, em parte são repassados às empresas privadas de transportes coletivos. Ou seja, o usuário paga duas vezes. Paga também por quem pega o ônibus de graça e paga, indiretamente, ao fazer as compras no supermercado, pois as empresas são obrigadas por lei a pagarem parte do valor do transporte aos seus funcionários, repassando essas despesas no preço final do produto comprado pelo “passageiro”. E o não usuário, por tabela, também paga. Veja na revista, a ideia de um sistema de transporte coletivo, que gera empregos, eficiente, transportando gente e não gado, somente sentada, com tarifa mais barata e deixando de gastar mais de 4 bilhões ao ano com as empresas de transporte coletivo, em São Paulo.
                                De quem é a culpa de tanta complexidade e injustiça? É do sistema Demoditalismo (salada de regime político), adotado no Brasil e em diversos outros países que acolhem as ordens dos genocidas, transmitidas pelo Sistema Glo’s de jornalismo (Globalização e Globalismo). Demoditalismo: Ditadura com máscara de Democracia e alma de socialismo. Democracia pelo direito que o cidadão tem de escolher seus representantes para fazerem leis ditatoriais, sem participação direta nas decisões políticas dos municípios, dos estados e da união. Democracia pela obrigação (ditadora) de escolher seus representantes e governantes, tendo como únicas opções, o voto em branco, a justificativa e a punição por abstinência e, autoritárias, mais uma vez, por ser obrigatória, a escolha de homens e mulheres políticos e não técnicos de cada área econômica e social.  Democracia por conceder a liberdade de expressão que a imprensa a transforma em fofoca, ao feitio do NR (eu dramatizo mas não modifico). Socialismo por investir no “Tudo pelo Social”, durante mais de 30 anos seguidos e insistindo nas práticas políticas de “todos por alguns”. Se investisse todos os esforços na geração de empregos, no “todos pelo trabalho”, o social teria sido atendido, com muito mais eficácia do que os programas sociais eleitoreiros, humilhantes, escravizantes, alienadores e insustentáveis. Demoditalismo, com quatro poderes entrando em conflito constantemente, incivilizados, um acusando o outro e o jornalismo colocando mais lenha na fogueira, onde o quinto poder, o povo é o único que sai queimado, sob todos os aspectos. Demoditalismo, por ter o povo, espécie de quatro patrões numa mesma empresa: Um Poder Judiciário que, sob leis instituídas pelo Poder Legislativo, absolve o criminoso e condena a vítima. Um Poder executivo que, sob essas mesmas leis, sacrifica o empregado para tentar salvar a empresa. Uma imprensa que se aproveita dessa complexidade e iniquidade para ganhar audiência, as custas da ignorância de parte dos “empregados”, para também salvar a sua empresa. Democracia do Povo é “Cada um por si e deus (município, estado, país) por todos”. Cidadão livre e independente para fazer escolhas individuais, atreladas às preferências e necessidades coletivas. Democracia do Povo é o quinto Poder, com todos os cinco poderes trabalhando pelo todo.
                    </p>
                            <h2 style={{ textAlign: 'center', paddingTop: '5px', color: '#000bd4', fontFamily: 'Calibri' }}>
                                O CÍRCULO VIRTUOSO E O CÍRCULO VICIOSO
                    </h2>
                            <p style={{ textAlign: 'justify', color: '#000', padding: '20px', fontSize: '20px', display: 'flex', flexWrap: 'unset', fontFamily: 'Garamond' }}>
                                O Sr. Vito Ozo tem uma pequena empresa com 18 funcionários e salário médio de 1.000 reais. Fabrica manualmente, 100 unidades ao mês de um produto que utiliza matéria prima de exportação e vende por 1.000 reais a unidade, faturamento de 100.000 reais. O lucro da empresa e a retirada de Seu Vito, é de 12.000 reais, ao mês. Seu Vito quer que a sua empresa cresça e resolve construir uma máquina, com capacidade para produzir 200 unidades ao mês. Seus funcionários terão que ser treinados para operarem a máquina, por essa razão utilizarão mais o raciocínio do que o esforço físico, se qualificando na própria empresa. Seu Vito Ozo é um empreendedor virtuoso, por isso quadruplicará o salário de seus funcionários, passando para 4.000 reais mensais. O lucro e a retirada aumentarão, conforme projeto descrito na revista. Seu Vito quer crescer ainda mais, então constrói outra máquina, mais sofisticada, com capacidade para produzir 400 unidades e admite mais 12 funcionários.
                                Seu lucro será de 72%. Desta forma, poderá dar um excelente desconto no preço para o cliente que comprar 2 ou mais unidades.  E assim, Seu Vito Ozo completou o círculo virtuoso: seus funcionários puderam também comprar o seu produto, pagou preço menor da matéria prima ao comprar maior quantidade, gerou mais 10 empregos, modernizou a sua empresa, criou mais produtos, como a fabricação de máquinas e pagou valores maiores de impostos, não gerou inflação e, ao contrário, o preço de venda ficou mais barato. Seu Vito Ozo não vê a hora que o Novo Simples seja sancionado para admitir mais 6 funcionários e Gan Har mais dinheiro, beneficiando todos os envolvidos com a pequena empresa.
                    </p>
                            <p style={{ textAlign: 'justify', color: '#000', padding: '20px', fontSize: '20px', display: 'flex', flexWrap: 'unset', fontFamily: 'Garamond' }}>
                                O Sr. Vicci Ozo tem uma pequena empresa com 18 funcionários e salário médio de 1.000 reais. Fabrica manualmente, 100 unidades ao mês de um produto que utiliza matéria prima de exportação e vende por 1.000 reais a unidade, faturamento de 100.000 reais. O lucro da empresa e a retirada de Seu Vicci, é de 12.000 reais, ao mês. Seu Vicci quer que a sua empresa cresça e resolve importar uma máquina, com capacidade para produzir 200 unidades ao mês. Seus funcionários terão que ser treinados para operarem a máquina, por essa razão utilizarão mais o raciocínio do que o esforço físico, se qualificando na própria empresa. Seu Vicci Ozo é um empreendedor vicioso, por isso, diz aos seus funcionários, que não haverá aumento de salário, pois está pagando o financiamento da máquina importada, que custou muito para sair e os juros são altíssimos. Depois de alguns meses a máquina quebra! A assistência técnica demora 10 dias para consertá-la. O preço da matéria prima teve
                                elevação no preço devido a quantidade baixa de compra. Desta forma Seu Vicci Ozo completou o círculo vicioso: diminuiu o seu lucro, não gerou mais empregos, demitiu 6 funcionários, chamou a mulher para ajudar, encostou o “negócio da China”, ficou devendo para o fornecedor da matéria prima, sonegou parte do Simples por uns tempos, depois não conseguiu mais pagá-lo, sujou o nome, seu CNPJ foi caçado, entrou na informalidade, mas com muita luta, abriu outra firma no nome da mulher, mas com uma produção muito pequena, teve que aumentar o preço do produto. Seu Vicci Ozo gostaria de ser igual ao seu Vito Ozo, mas foi traído pelas retrógradas leis instituídas por quem ele escolheu para representá-lo.
                    </p>
                            <h2 style={{ textAlign: 'center', paddingTop: '5px', color: '#000', fontSize: '25px' }}>
                                LISTA DOS CANDIDATOS, QUE AO SEREM ELEITOS AOS CARGOS DE PREFEITO E VEREADOR, TRABALHARÃO PARA IMPLANTAR A DEMOCRACIA DO POVO EM SEU MUNICÍPIO.
                    </h2>
                            <TabelaDePreco />
                            <br />
                        </div>
                    </div>
                </div>
            </div>
            <Footer />
        </div>
    );
}

CandidatosInscritos.propTypes = {
    classes: PropTypes.object
};

export default CandidatosInscritos;
